debug:
  logLevel: info
  flushLevel: trace

player:
  # Restrict movement for Player when casting aimed concentration spells
  restrictMovement: true
  # Speed modifier to apply to the current player speed when restrictMovement: true. 1 means no change, and 0.1 means 10 times slower.
  # Low values (0.1, 0.2) may cause isuses with TDM
  movementModifier: 0.4

npc:
  # Restrict movement for NPC when casting aimed concentration spells
  restrictMovement: true
  # Restrict npc turn rotation when casting aimed concentration spells so they won't aim you too fast allowing you to dodge
  restrictRotation: true
  # Disable tracking for dragon shouts
  lockDragonShous: true
  # Speed modifier to apply to the current npc speed when restrictMovement: true. 1 means no change, and 0.1 means 10 times slower
  movementModifier: 0.1
